image: node:10

stages:
  - test

run_tests:
  stage: test
  script:
    - node --version
    - npm --version
    - npm install github:nearprotocol/nearlib#nightshade
    - ls -lh node_modules/nearlib
    - npm install
    - npm run test
