image: node:10

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/

run_tests:
  stage: test
  script:
    - yarn test
