image: node:10

stages:
  - test

run_tests:
  stage: test
  tags: 
    - gcloud
  script:
    - yarn
    - NODE_ENV=ci yarn test

run_tests_staging:
  stage: test
  tags: 
    - gcloud
  script:
    - yarn
    - NODE_ENV=ci-staging yarn test
