name: Tests
on: push
jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        node-version: ['16']
    runs-on: ${{ matrix.platform }}
    env:
      NODE_ENV: ci
    steps:
      - uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        run: yarn && yarn lint && yarn test